### ISSUE TITLE
Consider using unique names for data dependency

### ISSUE THREAD

**Issue by jcheng5** [vegawidget/vegawidget#125]
In the course of responding to https://github.com/ramnathv/htmlwidgets/issues/367, I noticed that vegawidget makes use of the "attachment" feature of htmlwidgets. Fantastic!

https://github.com/vegawidget/vegawidget/blob/cb90c1a3782b2a853e53647ca2f0a37a65895a26/R/vegawidget.R#L134-L140

I suspect the fact that the dependency name is hardcoded to `data` means that if two vegawidgets exist on the same page (say, one Rmd document) and both make use of `base_url`, only one of them will succeed. If so, using a distinct name--perhaps derived from the `elementId`, if available--would fix it. (A random name would work as a fallback, sometimes that annoys people that need to commit the rendered output to source control)

**Comment by ijlyttle** [comment]
Credit for using this feature belongs to @AliciaSchep!

I'll look into incorporating the `elementId`.

Thanks!

**Comment by ijlyttle** [comment]
Just noting some things here for future-me.

As it turns out, using a local data dependency works *only* if you are working interactively; it does not work if you are knitting. There seem to be a couple of problems:

- specifying exactly where the data file will end up
- getting around CORS issues (using a `file` URL within a `http(s)` page)

I get the sense that these would have to be solved at the **htmltools** level - I think they have been discussing this for a while: https://github.com/rstudio/htmltools/issues/13

The "fix" in #141, which adds a unique identifier to the library seems to be moot because, interactively, there can be only one element. That said, I am inclined to leave the fix in anticipation of a larger being figured out (or revealed to me).

In #142, I added some documentation, and a warning that gets issues if you try to add a local dependency while knitting.
