### ISSUE TITLE
shiny interaction support

### ISSUE THREAD

**Issue by AliciaSchep** [vegawidget/vegawidget#13]
I am interested in what the intended shiny interaction support for this package is?

I have started exploring how to get some interactions from vegawidget into shiny.  I so far have a proof of concept of getting click events in a [branch of my fork](https://github.com/AliciaSchep/vegawidget/tree/shiny).  See test_app folder for an example app, and vegawidget.js for the implementation details. I haven't yet tested what happens when the plot is something other than a simple scatter plot, but it seems to work okay for a simple scatter plot.    

I am thinking that it would nice to be able to support:
* Click  and hover events (not necessarily tied to a vega-lite selection)
* Selections (if a selection has been defined in a spec, get the current status of that selection)

From initial exploration, 1 and 2 seem pretty tractable.  3 seems also doable but trickier -- would be a lot easier if https://github.com/vega/vega-lite/issues/1830 was implemented (or at least https://github.com/vega/vega-lite/issues/2790).  

At some point sending info from shiny back to widget would also be good, but I would guess that only getting info from widget to shiny could be a viable independent first step. I don't really understand how `signals` work in `vega` though so I am likely missing something important :smile:

**Comment by ijlyttle** [comment]
As you know, right now the support is simply the htmlwidgets boilerplate. I would like the support to be much more, so I'm glad you do, too 🙌- as for *actual* plans, it is a blank canvas (until now). I will have to take a look at your branch, but please keep going!

I think that wrapping our heads around selection could also be useful for `crosstalk` compatibility.

Another vague idea I have had about shiny is to try to mimic the `ggvis` support, in that parts of the `ggvis` (`vega`, as you know) object could be reactive. 

My brief conversation at the workshop seemed to imply that we would have to work with `signals` in `vega` - although it seems it would be nice to have the helper functions. One of these days I will have to sit down and fiddle with `vega` to start to figure it out for myself.

**Comment by AliciaSchep** [comment]
Some more thoughts on shiny interaction and possible API:

(1) Functions for adding 'listeners':
* `vw_add_event_listener(widget, event, handler)`:  event is a supported event type like 'click' or 'dblclick'.  handler is some javascript to do something.... would rely on user to know what javascript they want to run...
* `vw_add_shiny_event_listener(widget, event)`:  Rather than having to specify a JS handler for what to do on event, this would use a default handler that would expose the data associated with the event as {id}_{event}  in shiny (where id is the name of the output object in shiny, and event is the event name).
* `vw_add_signal_listener(widget, signal, handler)`:  signal is the name of a signal, and handler is some javascript. 
* `vw_add_shiny_signal_listener(widget, signal)`:  Similar to the `event` version, it would have a default handler for exposing the the signal value in shiny, tied to {id}_{signal}

These could be added either to the widget on render time, or after widget has been rendered (so that you could add them based on shiny input for example).  

(2) The `remove` equivalents of the `add` functions

(3) Functions for modifying data from shiny -- `change`, `insert` and `remove` methods from [Vega View]( https://github.com/vega/vega-view#data-and-scales).  The R helper function would likely also run `run` afterwards. Functions in R might be called something like `vw_insert_data`

(4) Function for binding a shiny ui element to a signal in a spec. This would wrap the `signal` functionality from [View API](https://github.com/vega/vega-view#view_signal). This reactivity in the vega plot would require having a spec with a signal defined. I have started experimenting with binding shiny ui to vega specs and think this functionality should be feasible.  

(5) Functions for 'listening to' vega-lite selections. Without helper function in vega-lite I am a bit nervous about this part because it seems to rely on understanding of the implementation of vega-lite selections, which might be subject to change....

@ijlyttle would be interested in your thoughts on proposed functionality above!

**Comment by ijlyttle** [comment]
So, I had thought that my day was going to be implementing the stuff form #15 ;) 

Let me dig in here a little bit and get myself a bit educated. I'm sure I will be back with some uninformed questions - but it's going to be a great day!

**Comment by ijlyttle** [comment]
@AliciaSchep, I have tried to make myself at least superficially aware of how this might all work, so I will beg your forgiveness in advance, should my questions or responses be uninformed.

First and foremost, I like the API - oddly enough, it seems very consistent where the API for the rest of the package is headed ;) The rest of my response is just me trying to wrap my head around things.

This seems like a good opportunity to tag in @haleyjeppson, who I am sure will be interested to test-drive your implementations. I don't want to speak too much for Haley, but I suspect that these foundational elements could be very useful for her to rely upon in her work.

In very broad terms, it looks like what you are proposing is a set of R functions to facilitate interactions between a vegawidget and the external JavaScript/DOM world. Shiny is the best-known example of such an external world, but there could be others, like crosstalk. I think (perhaps as you do) that we "need" to have the way to work with Shiny, but that if the general functions that you are developing can let someone compose a set of crosstalk tools, that's an even bigger win.

In points (1) and (2), I see (or infer) versions of functions for the Shiny case and for the general case.  In points (3) and (4), I see the Shiny case, but don't see anything implied for the general case. This is likely my ignorance: for these functions there would not be a difference, or would the general case does not need an R function defined for it? I ask this because I suspect that the `vw_data_` functions might be very interesting for Haley, but perhaps outside the Shiny context.

Would/could this approach play well with Shiny modules and the things is does with the id namespace?

It may sound like I am arguing in two different directions on Shiny (probably because I am). One tangential idea I have (if someone has not already implemented it) is to see if the Shiny UI elements could themselves be packaged as htmlwidgets, so that you could "talk" to Vega using Shiny UI, but being decoupled from the Shiny server. Could your proposal support such an implementation? (with apologies for taking this conversation all over the place)

As for point (5), I agree with your assessment that we would be dependent upon the internals of compilation to Vega of selections to signals. For my part, I would happy to accept anything you might provide on the Vega-Lite side, as along as we all (including downstream users) understand that this bit is experimental. On the flip side of this, perhaps this would give "us" an opportunity to influence how the Vega-Lite team decide to do things.

Also, for point (5), I seem to remember that Altair does its own thing for naming the selections and I don't know how we might go about getting those names programmatically so that someone could query their Altair chart for the name of a selection to be used with your Vega-Lite helpers.

I hope that all of my scattered questions can also serve to emphasize how enthusiastic and grateful I am for what you are doing.

Thanks!

**Comment by ijlyttle** [comment]
I agree, lots to think about, and I'm still not sure that my thoughts are well formed. To be clear, the extent of my experience developing for crosstalk is reading the documentation. 😓😄

You're right, I don't we could not adapt crosstalk as-is, for exactly the reasons you outline (spec vs. data, ...). That being said, I *think* there might be something there. For me, the key may be to supply specs with named datasets. Your proposal (3), modifying data, would require named data-sets (if I read [vega-view](https://github.com/vega/vega-view#view_change) correctly).

More concretely, Shiny is "today" and crosstalk is a "hazy possibility", so I don't want to get too-much in-the-way of what you are doing.

**Comment by sa-lee** [comment]
Any updates on this? I'm keen for the changes @AliciaSchep's fork to be merged into master as it would be super useful for the stuff I'm doing at the moment. 

Another question - what's the current preferred way of passing data into a spec from the R side? Does a user always do `list(values = df)` then the entire data frame gets written as json? Would it be possible to just pass a reference to the data and then only use the data required for the visualisation?

**Comment by ijlyttle** [comment]
Hi @sa-lee, for my part, I will be happy to look at a pull request as soon as @AliciaSchep thinks it's ready. 

On data frames, yes you can do `list(values = df)`, and the data frame will be written as JSON. You can also write the data frame as a named dataset, using sample data, for example. See: https://vega.github.io/vega-lite/docs/data.html#datasets

I'm sure you've seen this, that the vega-view api deals with these named datasets:
https://github.com/vega/vega-view#data-and-scales

Does this answer the question?

**Comment by ijlyttle** [comment]
That sounds great - I have just created a branch called `shiny-interaction`.

**Comment by ijlyttle** [comment]
Hi @sa-lee - let's fork the discussion of data-frame loading to a separate issue. I'll link to it here, once established.

**Comment by AliciaSchep** [comment]
@sa-lee Yes it'd be great if you added insert/remove/change methods!

**Comment by sa-lee** [comment]
I've started on these in my [fork](https://github.com/sa-lee/vegawidget/tree/shiny-interaction)  - the insert works, remove is a bit trickier since it can take a predicate function or a dataset (and in some cases the view doesn't seem to update based on the dataset unless you retrieve it with view.data()).

The other case that I think would be useful is to return the [current state](https://vega.github.io/vega/docs/api/view/#view_getState) of the view to shiny, `vw_observe_state()`

**Comment by AliciaSchep** [comment]
I have some recollection of trying to experiment with getting the current state but running into a roadblock in that the resulting object couldn't be passed directly to shiny via `Shiny.onInputChange`. As I didn't have an immediate use case in mind I didn't pursue further.  Another function to potentially expose would be `view.data`

**Comment by ijlyttle** [comment]
#51 has been merged into master - I think this starts us (oficially) down the path!
