### ISSUE TITLE
create and retrieve blocks

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#20]
this is already underway, but it may be useful to document some of the arguments I might have with myself.

**Comment by ijlyttle** [comment]
An idea for API to create and retrieve blocks

## Create block

Create a block using a spec

```r
#' @param browse `logical` when done, open the a browser to the block page
#' @param endpoint `character` defaults to "https://api.github.com"
#' @param block_host `character` defaults to "https://bl.ocks.org"
create_block <- function(spec, embed = vega_embed(), block = block_yaml(),
                         versions = vega_versions(major = FALSE), description = "",
                         readme = NULL, use_thumbnail = TRUE, use_preview = TRUE,
                         git_method = c("ssh", "https"), endpoint = NULL, env_pat = NULL,
                         block_host = NULL, quiet = FALSE, browse = TRUE) {

  spec
}

# returns gist information rather than spec
create_block_gistid <- function(spec, ...) {

  list(id, endpoint)
}
```

### Retrieve block, return as spec

```r
retrieve_block <- function(id, file = NULL, endpoint = NULL, env_pat = NULL) {

  # if we have a valid PAT use github API to return content or URL

 # if not do the best we can to  create a URL

  # result will be a `character`
  result
}
```

**Comment by ijlyttle** [comment]
We would expose helper functions: 

- `block_config()`

We have internal functions:

- `block_build_directory()`
- `block_index()`

**Comment by ijlyttle** [comment]
Question for you, @AliciaSchep: `block_create()` or `create_block()`?

- `create_block()` leads with verb
- `block_create()` suggests affinity with other block function, `block_retrieve()`

I have gone back-and-forth and cannot decide - do you have an opinion? Thanks!

**Comment by AliciaSchep** [comment]
Either way seems fine!  If you were to go with `create_block`, then it would probably make sense to switch to `retrieve_block` as well.  

Best choice maybe depends a bit on what pattern the other functions in package use... is goal to generally group related functionality that way?  

Alternatively, perhaps a package-wide prefix (e.g. `vw_`) might make sense (for everything but the main vegawidget function)?  In that case the pattern  prefix + verb as start of function might make the most sense to consistently use across package.  I think the prefix could be helpful for functions like `examine` and `to_svg` which might be more likely to be present in other packages due to their generality.

**Comment by ijlyttle** [comment]
Thanks!

I was lazy for not including `block_retrieve()` in the top part - my bad!

My first reaction to `vw_` was "grumble, grumble, that sounds like a bunch of work...", my second reaction was "you're probably right" 😳

Will have to ponder this one a bit - my current thought is to exempt `as_vegaspec()` as well, and maybe a few others like `vegawidgetOutput()` and `renderVegawidget()`.

**Comment by ijlyttle** [comment]
Given the resolution of #15, methinks this is complete, too.
