### ISSUE TITLE
dataframe: row-based vs. column-based

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#36]
This is forked from #13, as I think that, although this issue affects shiny, it is not limited to shiny.

As @sa-lee points out, column-based data-frames are more "R"-like, while Vega works in the world of row-based data-frames. Column-based is more space-efficient, while row-based makes it easier to deal with individual observations.

Bringing over a couple of Stuart's points:

>  There's definite room for runtime optimizations of loading data into the view. Two quick ones I can think of: 1. if list(values = df) only write out to json the data required for the marks etc. 2. sending dataframe to column oriented json and converting to row oriented lazily on the client. Serialising as column oriented json drastically reduces the size of the file being sent to the widget, and aligns more with R way of doing things.

**Comment by ijlyttle** [comment]
On point one (keeping only those columns that are used), I think this is a worthy goal, but could be an implementation nightmare. We would need a function to tell us, with certainty, which columns are used. Perhaps we could capture all the list elements named `"field"`, but I have this fear of missing an edge case and having it fail with no easy way to figure out why. 

For now, I would prefer that the user keep this responsibility to maintain the data-frame.

The second point on serialisation (or serialization, if you will 😉) - I think this gets a bit trickier for Vega because there are *so* many different places where data can be specified. In the htmlwidgets package, there is a [way to deal with this]( https://www.htmlwidgets.org/develop_advanced.html#htmlwidgets.dataframetod3), but this would be difficult to generalize, again, because there is not a single, unambiguous data-frame in a Vega spec.

I know I keep coming back to named datasets, but I think this is where such a thing might be accomplished. 

Happy to continue the conversation!

**Comment by sa-lee** [comment]
I'm not sure I understand where the other the entry points for data are outside of the `data` part of the spec. 

I agree that for now it's probably easier to have the user maintain the data frame, and since my understanding of vegawidgets is that it's a building block for other APIs it makes sense to have it follow the Vega way of doing things. As far as I can tell Vega generally expects row oriented json for data (as stated [here](https://beta.observablehq.com/@jheer/from-apache-arrow-to-javascript-objects)).

Re serialization I know we can convert on the js side with htmlwidgets, my point is that this might be a bottleneck for medium-biggish in memory data and would be worth benchmarking. 

Even with named datasets, some json eventually has to be sent client side but it would be a good idea to defer this.  Do you think it would be a good idea to have an entry point to this in vegawidgets as I partially referenced in #13?

**Comment by ijlyttle** [comment]
There can be multiple entry points for data when we have layered or concatenated specs. Each layer or concatenated element can have its own data, which then becomes very hard to keep track of - here's an [example](https://bl.ocks.org/ijlyttle/185913b949c36dbf140184d137cb1e3d), although it is very contrived.

This is a reason I am fond of named datasets - there is only one place they can be. The same can be said for a top-layer `data` element.

That being said, I think it would be a good idea to have such an entry point in vegawidgets, as long as we can be clear about the situations that could and could-not be supported.

**Comment by sa-lee** [comment]
Ok that makes sense - does that mean each layer has its own variable scope?  I guess I've been more focussed on vega than vegalite so I didn't realize this was possible. 

For my proposed loader and updaters they will only make sense if there is a top data element.

**Comment by ijlyttle** [comment]
When we get into variable-scopes, I'm afraid I don't have any firm answers. I suspect so, but I would not trust me to have the definitive answer.

By all means, focus on the top data element to get things working. Eventually, I think it may be useful to support named datasets as well, as this is also popular pattern to reduce data-duplication.

**Comment by ijlyttle** [comment]
I think this is taken care-of in the `Vegawidget.changeData()` function in `vegawidget.js` - which I hope to merge soon into master.

This function checks to see if a "data frame" is in row-based form or column-based form, then converts to row-based form if needed.
