### ISSUE TITLE
ES5 / ES6

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#44]
It looks like Vega/Vega-Lite may be moving from ES5 to ES6 [[slack link](https://vega-js.slack.com/archives/C0NG6SXFX/p1537148795000100)]. Not immediately, but at some point. We seem to rely on ES5 for just about everything we do outside the browser (I could be wrong here, please correct me as needed):

-	PhantomJS for image-rendering and knitr printing
-	V8 for compiling to Vega and (possibly soon) validating specs
-	RStudio IDE (released 1.1.x uses ES5, preview 1.2.x uses ES6)  
 
If/when Vega(-Lite) moves to ES6, I think we risk losing V8 and PhantomJS, as I don’t see comprehensive support for either for ES6.

This gets me to thinking if we could, or should, look at a chromium approach, as Altiar is doing – along the lines of [hrbrmstr/decapitated](https://github.com/hrbrmstr/decapitated). Perhaps using webdriver with a chromium driver. All ideas welcome 🙏

**Comment by AliciaSchep** [comment]
If we want to go that route, probably worth also exploring [RSelenium](https://github.com/ropensci/RSelenium).  Another approach might be to use [Babel](https://babeljs.io/docs/en/) to transpile the JS libs to be compatible with older browsers? Although IMO this seems like a problem to be solved when it becomes a real and not just hypothetical issue! Worth keeping an eye on though...

**Comment by ijlyttle** [comment]
Thanks for the alternatives - and for putting this into the right context: to solve the problem when we have the problem!

**Comment by ijlyttle** [comment]
I'm afraid it is now imminent - I removed myself from the oncoming bus: https://github.com/vega/vega-lite/issues/4283

The latest Vega, 4.4.0 is now ES6.

For the stuff we do in the browser and in the preview IDE, we are OK. For stuff we do headless, we have some work to do...

I think this affects:

- shiny testing
- image functions
- compiling to Vega
- validating specs, which we never quite got to

**Comment by AliciaSchep** [comment]
:fearful: :bus: 

Likely a stupid question, but would a node.js dependency for images/compiling be at all reasonable?  If so, maybe we can just use the command line utilities from [vega](https://vega.github.io/vega/usage/#cli) and [vega-lite](https://vega.github.io/vega-lite/usage/compile.html#cli)?  (i think we could likely not need the node-canvas dependency for png -- could get png by using the svg script and then using rsvg to convert).

**Comment by ijlyttle** [comment]
I am very open to using node here. I have to confess I would not know how to tell someone to install, or how to hook it up, so I would likely need your (or someone's) help here.

I do not like the idea of abandoning the shiny-testing or the spec-validation. 

I have this crazy idea, but I think I might wait until rstudio::conf to ask someone (well, someone else) in the know. The preview IDE uses an ES6 engine; it strikes me that there is at least the technical opportunity for RStudio to make a webdriver interface to it (or even to make their own package). I'm sure they have their reasons, but I would like to ask. I have [asked the question](https://community.rstudio.com/t/version-of-javascript-es5-es6-supported-by-the-ide-browser/14484) on the RStudio community, but no answer to the followup.

**Comment by AliciaSchep** [comment]
Ok will try out the node option! It technically would also be possible to do spec-validation that way (using ajv-cli for example) although if the intention was to do validation by default then would not want it to rely on other-wise optional dependency.

I agree that having some good modern solution to do this kind of thing in R would be ideal! It seems like current versions of V8 and webshot/webdriver will all become obsolete at some point unless updated with newer v8 and replacement for phantomjs, respectively

**Comment by AliciaSchep** [comment]
I am attempting to write JS scripts for compile & image functions that rely on node but don't require installing any npm packages not included in node itself (but instead take advantage of the JS code already in the R package).  Then there would also be a function to check if node is installed and if it is not, print a message directing someone to https://nodejs.org/en/download/ to download & install.

**Comment by AliciaSchep** [comment]
I have a proof-of-concept version of the `vw_to_vega` function using node instead of v8 in my branch: https://github.com/AliciaSchep/vegawidget/tree/nodescripts with the js script in vegawidget/inst/bin/compile_spec.js and the R code in `.vw_to_vega.vegaspec_vega_lite` modified to call that script.  It seems to work on my computer, among the things to be determined is what happens on other systems...

**Comment by ijlyttle** [comment]
Excellent - looking forward to taking this for a spin!

**Comment by AliciaSchep** [comment]
Now also have initial prototypes of the `vw_to_svg` and `vw_to_png` functions using this approach~  Next I'll try to see if this approach can handle data specified by url (#43).  I am thinking it might as the script I am adapting has a 'baseUrl' argument.

**Comment by ijlyttle** [comment]
Quick (ignorant) question - if someone has node installed, will they also need vega, etc. to be part of the node installation?

**Comment by AliciaSchep** [comment]
Nope!  Rather than just using the scripts included in vega/vega-lite, I am adapting those scripts so they don't call the vega / vega-lite npm packages but instead source the copies of vega & vega-lite already included in the package.  My goal is that it would not require installation of any npm packages. Partly because then we would have to worry about where to install those packages, version of those packages, etc...

**Comment by AliciaSchep** [comment]
After a bit of a struggle have figured out how to get the svgs to get made using remote (or local file) data in the spec.  (Side note: does local data file work for the widgets themselves? It doesn't appear to for me, but not sure if that is a known issue or if there is a known way to get it to work, etc...)

Now need to clean up the implementation, do some testing, etc.  A question on API @ijlyttle: With  previous approach `vw_to_png` gave the png as a URI rather than saving a file (with `vw_write_png` saving a file).  Should this approach do the same?  The approach I am using here doesn't actually go through a URI so it isn't as natural to have a function that gives that result...

**Comment by ijlyttle** [comment]
Super!! Especially about using the remote (and local) files!

I have never tried to use a local data-file myself, I will see if it works...

I think the reason that `vw_to_png()` gave the png as a URI was because the png was returned that way from the vega-view call. I see no specific reason to prefer the URI, and folks can always use `base64enc::dataURI()` if they are so inclined. By going this way, I think we could remove `vw_png_bin()`.

**Comment by AliciaSchep** [comment]
Not sure if the minified js files would be helpful... current approach is to use the path of the installed package in order to read in the vega(-lite) files in the node scripts.  Potentially vega/vega-lite files could be passed in as arguments to the scripts, but that doesn't necessarily seem better?

Another API question -- currently the `vw_to_svg` and friends are S3 functions that can take in either a spec or a widget instance itself. That is because under phantomjs approach the widget is itself used. With this node approach, the spec is the input. I think it would still be good to be able to pass in the widget object instead, but then the spec would be extracted from the widget.  Is there a helper function already to pull a spec out of a widget? (it would be `widget$x$chart_spec` right?).

**Comment by ijlyttle** [comment]
There is no helper function (as yet) to get a vegaspec directly from vegawidget. You are mostly right that it would be `widget$x$chart_spec`; `widget$x` is a JSON string that has an element `chart_spec`. There is an internal function, `.as_list.json()` (wrapper to `jsonlite::fromJSON()`, with defaults set up), that would get you a list with elements `chart_spec` and `embed_options`. From there, you could use `as_vegaspec(chart_spec)`.

I will make a note to take out the minified stuff.

**Comment by AliciaSchep** [comment]
@ijlyttle any learnings from rstudio conf on es6 support for things like shinytest?

**Comment by ijlyttle** [comment]
Yes! I will write more when I get my brain back, but the short-term answer is what you originally suggested - to use Babel. The longer term answer is that they are looking at getting webdriver to work with chromium - they see that they have to do it (I was not telling them anything new). I'll send more details by email.

**Comment by AliciaSchep** [comment]
@ijlyttle another implication of the es6 is that the knitr rendering in non-html does not work (e.g. in README.Rmd) as that relies on webshot / phantomjs

**Comment by ijlyttle** [comment]
One crazy idea I had, which I should look at more closely, was to try to intercept the knitr-rendering to non-html calls, then patch in calls to our functions for creating images. The idea had been on the backburner, but his might bring it forward...

**Comment by AliciaSchep** [comment]
I don't think that's so crazy an idea :) Seems worth exploring at least!

**Comment by ijlyttle** [comment]
I think the "big issue" here is settled, and we have been opening smaller issues, as they present themselves.
