### ISSUE TITLE
Initial update to VL3

### ISSUE THREAD

**Issue by ijlyttle** [vegawidget/vegawidget#65]
Continuing from [#56](https://github.com/vegawidget/vegawidget/issues/56#issuecomment-451685754):

Things being checked will denote them being "done" in the `develop` branch - issue will be closed upon being merged into `master`:

- [x] VL3 itself
- [x] in the absence of a solution, remove shiny tests 😢
- [x] update README
- [x] we can remove promise polyfills and other fixes (we will have to require RStudio IDE 1.2)
- [x] update any tooltip-references in documentation
- [x] node.js "stuff" @AliciaSchep is working on for images, compilation (and validation?)
- [ ] `addDataListener()`

Start writing using ES6 constructs - at our own pace

**Comment by ijlyttle** [comment]
Question: do we need to use the "patched" vega-embed [[link](https://github.com/vegawidget/vegawidget/blob/4b0ff787f42da58389a7a40fb19587e9df2962bb/data-raw/infrastructure.Rmd#L204)] and the non-minified vega.js?

**Comment by sa-lee** [comment]
what's the goal/spec of `addDataListener()`, to listen to the data signal from vega and send back to R? I had a sketch of something along those lines in easel that I could contribute if you like

**Comment by AliciaSchep** [comment]
@ijlyttle re the "patched" vega-embed -- I don't think that will be needed anymore.  That issue should have been fixed with newer Rstudio versions, and since we'll be requiring newer version anywa that shouldn't be a problem anymore.  But we should of course test :) 

For the non-minified vega.js I suspect / hope it might also not be an issue with newer rstudio version... but again some testing on different platforms can confirm (I know that was an issue on my computer / rstudio in particular, so can test with newer version of rstudio to check)

**Comment by ijlyttle** [comment]
@sa-lee I was thinking just to use vega-view's [addDataListener]( https://vega.github.io/vega/docs/api/view/#view_addDataListener) then hook the result up to a reactive - much like the event and signal listeners. Could you point me to what you did in easel?

**Comment by ijlyttle** [comment]
@AliciaSchep I'll make a quick commit to `develop` to remove the "patch" and to go with the minified Vega - happy for us to test for a little while to see if the "water is safe".

My idea is to claim that we work with the preview 1.2 version of the RStudio IDE - perhaps that's a starting point.
